[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "turismo"
dynamic = ["version"]

[tool.setuptools_scm]
root = ".."  # Relative path to git repo root directory
