[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "turismo"
dynamic = ["version"]
dependencies = [
  "googlemaps",
]

[tool.setuptools_scm]
root = ".."  # Relative path to git repo root directory
